feat: add upper range

diff --git a/test b/test
--- a/test
+++ b/test
@@ -14,15 +14,15 @@ cleanup() {
 trap cleanup EXIT
 rm -rf $TMP_DIR && mkdir -p $TMP_DIR && cd $TMP_DIR
 
-stats() {
+stats() { # runs the test and creates a `received.txt`
   echo "" >receieved.txt && eval $STATS $@ >>receieved.txt
   TITLE="\033[0;37m$@\033[1;0m"
 }
 
-assert() {
+assert() { # checks `received.txt` against $EXPECT
   echo "$EXPECT" >expected.txt
   diff -y -W 70 receieved.txt expected.txt >/dev/null
-  local RC=$?
+  local RC=$? # diff's return code. 0 means ok
   [[ $RC == 0 ]] && echo "$PASS $TITLE" || echo "$FAIL $TITLE"
   [[ $RC -ne 0 ]] && cat receieved.txt && exit 1
 }
@@ -33,7 +33,8 @@ X ~ B(10, 0.2)
 expected  | 2
 variance  | 1.6
 P(X = 4)  | 0.088080384
-P(X <= 4) | 0.9672065024"
+P(X <= 4) | 0.9672065024
+P(X > 4)  | 0.0327934976"
 assert
 
 stats nbinom 2 0.2 4
@@ -42,7 +43,8 @@ X ~ NB(2, 0.2)
 expected  | 8
 variance  | 40
 P(X = 4)  | 0.08192
-P(X <= 4) | 0.34464"
+P(X <= 4) | 0.34464
+P(X > 4)  | 0.65536"
 assert
 
 stats geom 0.2 4
@@ -51,7 +53,8 @@ X ~ G(0.2)
 expected  | 5
 variance  | 20
 P(X = 4)  | 0.1024
-P(X <= 4) | 0.5904"
+P(X <= 4) | 0.5904
+P(X > 4)  | 0.4096"
 assert
 
 stats pois 4.2 4
@@ -60,7 +63,8 @@ X ~ Poisson(4.2)
 expected  | 4.2
 variance  | 4.2
 P(X = 4)  | 0.1944236517
-P(X <= 4) | 0.5898270213"
+P(X <= 4) | 0.5898270213
+P(X > 4)  | 0.4101729787"
 assert
 
 stats unif 1.9 4.2 4
@@ -69,7 +73,8 @@ X ~ U(1.9, 4.2)
 expected  | 3.05
 variance  | 0.4408333333
 pdf @ 4   | 0.4347826087
-P(X <= 4) | 0.9130434783"
+P(X <= 4) | 0.9130434783
+P(X > 4)  | 0.0869565217"
 assert
 
 stats unif 1.9 4.2 4 4.1
@@ -79,7 +84,9 @@ expected        | 3.05
 variance        | 0.4408333333
 pdf @ 4         | 0.4347826087
 pdf @ 4.1       | 0.4347826087
-P(4 < X <= 4.1) | 0.0434782609"
+P(X <= 4)       | 0.9130434783
+P(4 < X <= 4.1) | 0.0434782609
+P(X > 4.1)      | 0.0434782609"
 assert
 
 stats exp 1.9 2.5 2.6
@@ -89,7 +96,9 @@ expected          | 0.5263157895
 variance          | 0.2770083102
 P(X = 2.5)        | 0.0164382209
 P(X = 2.6)        | 0.0135937369
-P(2.5 < X <= 2.6) | 0.0014970968"
+P(X <= 2.5)       | 0.9913483048
+P(2.5 < X <= 2.6) | 0.0014970968
+P(X > 2.6)        | 0.0071545984"
 assert
 
 stats exp 1.9 2.5
@@ -98,7 +107,8 @@ X ~ Exp(1.9)
 expected    | 0.5263157895
 variance    | 0.2770083102
 P(X = 2.5)  | 0.0164382209
-P(X <= 2.5) | 0.9913483048"
+P(X <= 2.5) | 0.9913483048
+P(X > 2.5)  | 0.0086516952"
 assert
 
 stats exp 1.9
@@ -117,9 +127,11 @@ P(X = 1)      | 0.2841803765
 P(X = 3)      | 0.0063573344
 P(X = 4)      | 0.0009508577
 P(X = 5)      | 0.0001422185
+P(X <= 1)     | 0.8504313808
 P(1 < X <= 3) | 0.1462226538
 P(3 < X <= 4) | 0.002845514
-P(4 < X <= 5) | 0.0004255996"
+P(4 < X <= 5) | 0.0004255996
+P(X > 5)      | 0.0000748518"
 assert
 
 stats norm 1.9 1 3
@@ -128,7 +140,8 @@ X ~ N(1.9, 1²)
 expected  | 1.9
 variance  | 1
 P(X = 3)  | 0.217852177
-P(X <= 3) | 0.864333939"
+P(X <= 3) | 0.864333939
+P(X > 3)  | 0.135666061"
 assert
 
 stats inorm 1.9 1 left 0.3
